//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Пр12
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> ReviewID { get; set; }
        public int ReasonID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Review Review { get; set; }
        public virtual TypeOfComplaint TypeOfComplaint { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public string BadUser => GetUser();

        public string GetUser()
        {
            if (Book != null)
            {
                return Book.User.Name;
            }
            if (Review != null)
            {
                return string.Empty;
            }
            return User1.Name;
        }
    }
}
