//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Пр12
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILM_IN_GENRE
    {
        public int ID_FILM_GENRE { get; set; }
        public int id_film { get; set; }
        public int id_genre { get; set; }
    
        public virtual FILM FILM { get; set; }
        public virtual GENRE GENRE { get; set; }
    }
}
