//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Пр12
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FILM()
        {
            this.FILM_IN_GENRE = new HashSet<FILM_IN_GENRE>();
            this.SESSIONS = new HashSet<SESSIONS>();
        }
    
        public int ID_FILM { get; set; }
        public string IMAGE_PATH { get; set; }
        public string NAME_FILM { get; set; }
        public decimal RATING_FILM { get; set; }
        public System.DateTime START_FILM { get; set; }
        public int id_agerating { get; set; }
        public string DESCRIPTION { get; set; }
        public int genre { get; set; }
    
        public virtual AGERATING AGERATING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILM_IN_GENRE> FILM_IN_GENRE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SESSIONS> SESSIONS { get; set; }
    }
}
