//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Пр12
{
    using System;
    using System.Collections.Generic;
    
    public partial class HALL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HALL()
        {
            this.SEAT = new HashSet<SEAT>();
            this.SESSIONS = new HashSet<SESSIONS>();
        }
    
        public int ID_HALL { get; set; }
        public int id_rate { get; set; }
        public string HALL_NAME { get; set; }
    
        public virtual HALL_RATING HALL_RATING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEAT> SEAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SESSIONS> SESSIONS { get; set; }
    }
}
