//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Пр12
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<BookInGenre> BookInGenre { get; set; }
        public virtual DbSet<Complaint> Complaint { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<ReadingList> ReadingList { get; set; }
        public virtual DbSet<RequestForAuthor> RequestForAuthor { get; set; }
        public virtual DbSet<RequestForDefrosting> RequestForDefrosting { get; set; }
        public virtual DbSet<Review> Review { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<StatusForLists> StatusForLists { get; set; }
        public virtual DbSet<StatusForUser> StatusForUser { get; set; }
        public virtual DbSet<TypeOfComplaint> TypeOfComplaint { get; set; }
        public virtual DbSet<TypeOfDefrosting> TypeOfDefrosting { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
