//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Пр12
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public int ID_ORDER { get; set; }
        public int id_cart { get; set; }
        public int id_customer { get; set; }
        public decimal PRICE_ORDER { get; set; }
    
        public virtual CART CART { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
