//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Пр12
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestForDefrosting
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> BookID { get; set; }
        public string Reason { get; set; }
        public int RequestStatusID { get; set; }
        public int TypeID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual StatusForUser StatusForUser { get; set; }
        public virtual TypeOfDefrosting TypeOfDefrosting { get; set; }
        public virtual User User { get; set; }
    }
}
