//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Пр12
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEAT_IN_SESSION
    {
        public int ID_SEAT_IN_SESSION { get; set; }
        public int id_seat { get; set; }
        public int id_session { get; set; }
        public bool STATUS { get; set; }
    
        public virtual SEAT SEAT { get; set; }
        public virtual SESSIONS SESSIONS { get; set; }
    }
}
