//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Пр12
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEAT_IN_SESSION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEAT_IN_SESSION()
        {
            this.SESSIONS = new HashSet<SESSIONS>();
        }
    
        public int ID_SEAT_IN_SESSION { get; set; }
        public int id_seat { get; set; }
        public int is_session { get; set; }
        public string STATUS { get; set; }
    
        public virtual SEAT SEAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SESSIONS> SESSIONS { get; set; }
    }
}
