//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Пр12
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESSIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SESSIONS()
        {
            this.SEAT_IN_SESSION = new HashSet<SEAT_IN_SESSION>();
            this.TICKET = new HashSet<TICKET>();
        }
    
        public int ID_SESSION { get; set; }
        public System.DateTime DATE_SESSION { get; set; }
        public int id_film { get; set; }
        public int id_hall { get; set; }
    
        public virtual FILM FILM { get; set; }
        public virtual HALL HALL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEAT_IN_SESSION> SEAT_IN_SESSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKET> TICKET { get; set; }
    }
}
