//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Пр12
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET
    {
        public int ID_TICKET { get; set; }
        public decimal TOTAL_PRICE { get; set; }
        public int id_session { get; set; }
        public int id_customer { get; set; }
        public int id_seat { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual SESSIONS SESSIONS { get; set; }
    }
}
