//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Пр12
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOVAR_IN_ORDER
    {
        public int ID_TOVAR_IN_ORDER { get; set; }
        public int id_tovar { get; set; }
        public int id_order { get; set; }
        public int Quantity { get; set; }
        public decimal Unit_Price { get; set; }
    
        public virtual ORDER ORDER { get; set; }
        public virtual TOVAR TOVAR { get; set; }
    }
}
